### ISSUE TITLE
Pets: animal facts should not be repeated

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#100]
The same animal fact should not be given more than once during a conversation.

**Example**

U: yes

S: Contrary to popular belief, dogs aren’t color blind; they can see shades of blue, yellow, green and gray. The color red registers on a grayscale in a dog’s vision. Do you want to know more?

U: yes

S: Contrary to popular belief, dogs aren’t color blind; they can see shades of blue, yellow, green and gray. The color red registers on a grayscale in a dog’s vision. Do you want to know more?

**Comment by dongxiangjue** [comment]
It was designed not to be repeated, especially in two continuous turns. I updated it with another method. It should be better.
