### ISSUE TITLE
Pets (highest priority): Need another possible starting sequence that doesnt rely on user invokation

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#101]
It should be possible to start the Pets component without the user explicitly having to say some animal. This will be useful when suggesting topics to the user, instead of forcing them to pick a topic themselves (which people are not enjoying based on the logs. )

Add logic (a new State and appropriate system and user transitions) to the Pets component that enables a generic opening to Pets, like "ok, i was curious about this. Do you have any pets at home?"

**Comment by dongxiangjue** [comment]
Updated.
