### ISSUE TITLE
Pets: doesnt handle "i dont have a pet"

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#102]
E: that ' s great! I love horse ! actually,  my favorite pet is german shepherd dog. Do you have any pets at your home now? If you have, What is it? is it a cat, a dog or other types of pets? 

U: i don't have a pet

E: Wow! Sounds interesting. Although I am not quite familiar with this kind of pets, I guess it must have a cute name. How did you choose the name?

**Comment by dongxiangjue** [comment]
The state machine only handles {no, nope, dont} without {don't}. I will ask James for help.
