### ISSUE TITLE
Sports: Repetition

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#113]
I am glad that we share same interest! I love watching NBA. Do you watch NBA?

nfl

I really like basketball because I had a lot of fun watching NBA. However, I have never physically played basketball as a robot. Is there anything that you want me to learn about basketball outside of NBA?

no

I really like basketball because I had a lot of fun watching NBA. However, I have never physically played basketball as a robot. Is there anything that you want me to learn about basketball outside of NBA?

no

thanks for your opinion. I will keep it in mind and learn more about it when I got some time. Besides basketball, I could also talk about recent movies or update you with recent music.

video games

we have talked a lot about basketball. Besides basketball, I could also talk about recent movies or update you with recent music. do you want to talk about something else

ok

**Comment by sefinch** [comment]
Similar to issue #96 but the last two sports responses are also pretty much repetitions of each other in this example too.

**Comment by Programmer01001101** [comment]
Thanks for pointing it out. I actually created this repetition intentionally. This repetition does not go on forever. However, the component should indeed exit when user says "movie, news, music, pet" explicitly. I have fixed this issue
