### ISSUE TITLE
Music: needs better profanity handling

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#114]
Music's common utterance that recommends three songs is frequently being flagged as profane by Amazon's classifier due to profanity in the song titles. Music needs to filter out these songs from its recommendation, so we can get through the classifier and let the user keep talking to music.

Example:
"Here are some popular  tracks this week according to the Billboards: dance monkey by tones and i, everything i wanted by billie eilish, and good as hell by lizzo, are in top 20."

**Comment by sergey-volokhin** [comment]
word "hell" added to the stopword list on ec2 crawling script, songs should be updated today at 4am. 
as far as I know, "hell" is the only word being flagged from this year, which wasn't flagged last year (if that's incorrect, please correct me).
