### ISSUE TITLE
Movies does not handle user input after asking "what was the last movie you liked?"

### ISSUE THREAD

**Issue by jdfinch** [emora-chat/emora#116]
There seems to be a pretty persistent issue where movies defaults to suggesting 3 movies to users instead of responding to their actual utterance (even just to acknowledge that the movie isn't recognized).

**Stats**

Low rated conversations: 129
Low rated convos w/ movie: 50
Low rated convos w/ movie and issue: 34

**Examples of low rated conversations with this issue (with conversation ids):**

loading convos_2020-02-21_2020-02-22.txt

2cf7327ed044843ec72f2e58ed2b82adb94ec49a66cb900858823f9901d215dc
E: Ok. I can tell you movie plot and reviews, fetch ratings from rotten tomatoes, check for fresh movies in the theatres, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: dora and the lost legend  (IntentRequest)
E: I have found some popular  new  movies : incitement, uncut gems, and honeyland.  Do you want to know more about honeyland?  (state_machine)

940dae23e5d7f75a3239a04f1c3331303b94b599b584ca8d5b763e03511930ea
E: You know, I have been thinking,    Ok. I can check for fresh movies in the theatres, fetch ratings from rotten tomatoes, tell you movie plot and reviews, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: rocket man  (IntentRequest)
E: I have found some popular  new  movies : goldie, honeyland, and portrait of a lady on fire.  Do you want to know details about portrait of a lady on fire?  (state_machine)

f6c5bc4c1bdfa41fa7eac3b37b83cd022ef8d6af81b15dd7e32d94968753cfcf
E: Really? You are not scared of that? Maybe you know something I don't.  .   I have really enjoyed talking about these inventions with you. Let me think.    Ok. I can fetch ratings from rotten tomatoes, tell you movie plot and reviews, give general movie-related information, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: her  (IntentRequest)
E: I have found some popular  new  movies : vitalina varela, incitement, and portrait of a lady on fire.  Would you like me to tell you about portrait of a lady on fire?  (state_machine)

de5d8c08c06bdc2760d6de04625963a3bb46f47850e13a5d11164c6dcb7114bd
E: Let's see.     Ok. I can fetch ratings from rotten tomatoes, check for fresh movies in the theatres, tell you movie plot and reviews, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: sonic the hedgehog  (IntentRequest)
E: Here are three  new  movies  that I recommend: knives out, goldie, and incitement.  Would you like to know more about incitement?  (state_machine)

0bd3754e7f9ebf960e32e7c4fd1bea616613e8942765c1c28ad78b3c2084a97f
E: I see. That is an interesting point. Personally, I don't think I could be one of the first people to try it out.  .   I have really enjoyed talking about these inventions with you. Let me think.    Ok. I can give general movie-related information, tell you movie plot and reviews, fetch ratings from rotten tomatoes, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: racing in the rain  (IntentRequest)
E: Here are three  new  movies  that I recommend: vitalina varela, a beautiful day in the neighborhood, and knives out.  Do you want me to tell you about knives out?  (state_machine)

b0545688d03f3902b2e1de38345e10ea6bfa45eea5fc9bd59b84bffdcf918efd
E: Yeah, I definitely need other people to test it out first, too. Safety is important, for sure.  .   I have really enjoyed talking about these inventions with you. You know, I have been thinking,    Ok. I can check for fresh movies in the theatres, give general movie-related information, tell you movie plot and reviews, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: so nineteen seventeen that was a good movie  (IntentRequest)
E: I have found some popular  new  movies : a beautiful day in the neighborhood, incitement, and goldie.  Would you like to know details about goldie?  (state_machine)

12b837b974e708961af7c245fb38b5c6961830ec13a9f896e14396e41d0ade65
E: You would volunteer so early? That is so courageous! I don't think I could gather the courage to do that.  .   I have really enjoyed talking about these inventions with you. Let's see.     Ok. I can check for fresh movies in the theatres, fetch ratings from rotten tomatoes, tell you movie plot and reviews, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: toy story four cause that was the funniest movie ever  (IntentRequest)
E: I have found some popular  new  movies : vitalina varela, pain and glory, and incitement.  Do you want to know more about incitement?  (state_machine)

121576ff8029d0bfd6b0ac09229415fc005731aca5e8a5512677404cb1aee477
E: You would volunteer so early? That is so courageous! I don't think I could gather the courage to do that.  .   I have really enjoyed talking about these inventions with you. You know, I have been thinking,    Ok. I can fetch ratings from rotten tomatoes, check for fresh movies in the theatres, tell you movie plot and reviews, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: i wanna know if you like come  (IntentRequest)
E: Here are three  new  movies  that I recommend: knives out, incitement, and pain and glory.  Would you like to know more about pain and glory?  (state_machine)

e4542c87591d6db997dc6129b90ef6fd17cf91286a64ae29ecf664149bdd833d
E: Oh boy. It makes me shake just thinking about it!  .   I have really enjoyed talking about these inventions with you. Let's see.     Ok. I can fetch ratings from rotten tomatoes, check for fresh movies in the theatres, give general movie-related information, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: frozen two  (IntentRequest)
E: I have found some popular  fresh  movies : a beautiful day in the neighborhood, parasite, and pain and glory.  Do you want to know more about pain and glory?  (state_machine)

9680c593214d1670e6cafe5f8ed766f3bee7919fdab661eef4bace03cbb2ad3d
E: I see. That is an interesting point. Personally, I don't think I could be one of the first people to try it out.  .   I have really enjoyed talking about these inventions with you. You know, I have been thinking,    Ok. I can tell you movie plot and reviews, give general movie-related information, fetch ratings from rotten tomatoes, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: star trek  (IntentRequest)
E: Here are three  fresh  movies  that I recommend: pain and glory, a beautiful day in the neighborhood, and goldie.  Do you want to know details about goldie?  (state_machine)

6a92baf286b2c58b407603ac64bb375c451406a0d8d3fb5ef8a8062f662ac5a8
E: Yeah, I definitely need other people to test it out first, too. Safety is important, for sure.  .   I have really enjoyed talking about these inventions with you. You know, I have been thinking,    Ok. I can fetch ratings from rotten tomatoes, check for fresh movies in the theatres, tell you movie plot and reviews, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: avengers infinity war  (IntentRequest)
E: Here is a good fresh animation movie I think you might enjoy: weathering with you. It has rating 90 out of 100 on rotten tomatoes. Would you like to know details about weathering with you?  (state_machine)

425b588e581af030b59cb693f63f325b3209c531b2aa559da3de942b7ee58a70
E: I see. That is an interesting point. Personally, I don't think I could be one of the first people to try it out.  .   I have really enjoyed talking about these inventions with you. You know, I have been thinking,    Ok. I can check for fresh movies in the theatres, give general movie-related information, tell you movie plot and reviews, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: willy wonka and the chocolate factory  (IntentRequest)
E: I have found some popular  new  movies : a beautiful day in the neighborhood, goldie, and premature.  Would you like to know details about premature?  (state_machine)

7a018c6bccf2e0e17825c10b70b22365c2baaecd490059d03f127de1cad453c0
E: Really? You are not scared of that? Maybe you know something I don't.  .   I have really enjoyed talking about these inventions with you. Let's see.     Ok. I can check for fresh movies in the theatres, fetch ratings from rotten tomatoes, tell you movie plot and reviews, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: play flushed away  (IntentRequest)
E: I have found some popular  fresh  movies : vitalina varela, goldie, and a beautiful day in the neighborhood.  Would you like to know more about a beautiful day in the neighborhood?  (state_machine)

44fd794500b938d5b4d59244cfa969137053ca48edccd1e623d2b125a16d1892
E: I see. That is an interesting point. Personally, I don't think I could be one of the first people to try it out.  .   I have really enjoyed talking about these inventions with you. Let me think.    Ok. I can check for fresh movies in the theatres, give general movie-related information, tell you movie plot and reviews, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: the matrix frozen two frozen two  (IntentRequest)
E: Here are three  fresh  movies  that I recommend: knives out, vitalina varela, and goldie.  Do you want me to tell you about goldie?  (state_machine)

08812a1f577d878a49a4ef5fa2829080bcd890db55fd36bfa1a968bb831e9439
E: You would volunteer so early? That is so courageous! I don't think I could gather the courage to do that.  .   I have really enjoyed talking about these inventions with you. Let me think.    Ok. I can check for fresh movies in the theatres, fetch ratings from rotten tomatoes, tell you movie plot and reviews, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: little women  (IntentRequest)
E: I have found some popular  new  movies : premature, honeyland, and incitement.  Do you want me to tell you about incitement?  (state_machine)

293c4006481e0a0df8993e8c496953ae992b3ca61e34159d696aa2ba03fcb48d
E: Yeah, I definitely need other people to test it out first, too. Safety is important, for sure.  .   I have really enjoyed talking about these inventions with you. Let me think.    Ok. I can fetch ratings from rotten tomatoes, give general movie-related information, check for fresh movies in the theatres, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: i want to say knives out but i wasn't crazy about it  (IntentRequest)
E: I have found some popular  new  movies : portrait of a lady on fire, goldie, and a beautiful day in the neighborhood.  Do you want to know details about a beautiful day in the neighborhood?  (state_machine)

a1f772067fb406ce5f913ec4391934ee7f9d691b2ffc03f30b2e01896872f3be
E: Yeah, I definitely need other people to test it out first, too. Safety is important, for sure.  .   I have really enjoyed talking about these inventions with you. You know, I have been thinking,    Ok. I can fetch ratings from rotten tomatoes, tell you movie plot and reviews, check for fresh movies in the theatres, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: upon the mall  (IntentRequest)
E: I have found some popular  fresh  movies : incitement, pain and glory, and premature.  Would you like to know details about premature?  (state_machine)

f4ff2e8d8d14b8f5e92f4376a4890ab0a6396f2f4f1e2daff215599ff32ba940
E: Oh boy. It makes me shake just thinking about it!  .   I have really enjoyed talking about these inventions with you. Let me think.    Ok. I can give general movie-related information, fetch ratings from rotten tomatoes, tell you movie plot and reviews, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: secretariant  (IntentRequest)
E: I have found some popular  fresh  movies : knives out, goldie, and pain and glory.  Would you like to know more about pain and glory?  (state_machine)

733f97ca7eb68bb0e52b3c04e528fb74cd5664080368feb67f9fa0405914f700
E: That is a good point, for sure. I never thought of it like that.  .   I have really enjoyed talking about these inventions with you. Let me think.    Ok. I can fetch ratings from rotten tomatoes, give general movie-related information, check for fresh movies in the theatres, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: harry potter and the sorcerer's stone  (IntentRequest)
E: I have found some popular  new  movies : incitement, premature, and vitalina varela.  Do you want me to tell you about vitalina varela?  (state_machine)

06b8cce5d36d88400b7496a635635028cfa94b8d00666398b558c9387830a0e5
E: I see. That is an interesting point. Personally, I don't think I could be one of the first people to try it out.  .   I have really enjoyed talking about these inventions with you. Let me think.    Ok. I can give general movie-related information, tell you movie plot and reviews, fetch ratings from rotten tomatoes, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: chasing happiness  (IntentRequest)
E: Here are three  fresh  movies  that I recommend: incitement, portrait of a lady on fire, and pain and glory.  Do you want to know details about pain and glory?  (state_machine)

2975afd4646bca4a1c1dce98edcaaa441ffe477720b714f7be09c065d025266f
E: Oh boy. It makes me shake just thinking about it!  .   I have really enjoyed talking about these inventions with you. Let's see.     Ok. I can fetch ratings from rotten tomatoes, check for fresh movies in the theatres, give general movie-related information, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: i can't remember the name of it  (IntentRequest)
E: Here are three  fresh  movies  that I recommend: vitalina varela, goldie, and incitement.  Do you want to know more about incitement?  (state_machine)

357a1ea44201ec62455f0708d904b99d94d7ce65ef3833013ecb1bb327ae2de7
E: Yeah, I definitely need other people to test it out first, too. Safety is important, for sure.  .   I have really enjoyed talking about these inventions with you. Let me think.    Ok. I can fetch ratings from rotten tomatoes, check for fresh movies in the theatres, tell you movie plot and reviews, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: nineteen seventy  (IntentRequest)
E: Here are three  new  movies  that I recommend: knives out, pain and glory, and parasite.  Would you like me to tell you about parasite?  (state_machine)

e2be25f146dbd51eb9bba27bd14b117a1413000ce2a87bc443e9bfb67308ddb7
E: Yeah, I definitely need other people to test it out first, too. Safety is important, for sure.  .   I have really enjoyed talking about these inventions with you. You know, I have been thinking,    Ok. I can fetch ratings from rotten tomatoes, give general movie-related information, check for fresh movies in the theatres, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: i don't like any of them  (IntentRequest)
E: Here are three  fresh  movies  that I recommend: portrait of a lady on fire, goldie, and pain and glory.  Would you like to know more about pain and glory?  (state_machine)

9abcf598194054c6a3894b62fead13e5af72a1ea7e460700de84fb3d9d7fd16d
E: I see. That is an interesting point. Personally, I don't think I could be one of the first people to try it out.  .   I have really enjoyed talking about these inventions with you. Let me think.    Ok. I can tell you movie plot and reviews, fetch ratings from rotten tomatoes, give general movie-related information, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: i agree you  (IntentRequest)
E: Here are three  new  movies  that I recommend: premature, goldie, and incitement.  Do you want to know details about incitement?  (state_machine)

ceab3b055b27142af58014800ca63815bebc0ce48cf33720a1bb3a3065ad79d4
E: Yeah, I definitely need other people to test it out first, too. Safety is important, for sure.  .   I have really enjoyed talking about these inventions with you. Let me think.    Ok. I can tell you movie plot and reviews, give general movie-related information, check for fresh movies in the theatres, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: once upon a time in hollywood  (IntentRequest)
E: I have found some popular  fresh  movies : knives out, incitement, and pain and glory.  Do you want to know more about pain and glory?  (state_machine)

64aa5658eeca94c65be410de4dc1a9203255aaea07cc605b2146cf8bd575cb25
E: You would volunteer so early? That is so courageous! I don't think I could gather the courage to do that.  .   I have really enjoyed talking about these inventions with you. You know, I have been thinking,    Ok. I can tell you movie plot and reviews, give general movie-related information, check for fresh movies in the theatres, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: what was that alexa  (IntentRequest)
E: I have found some popular  new  movies : pain and glory, citizen k, and a beautiful day in the neighborhood.  Would you like to know more about a beautiful day in the neighborhood?  (state_machine)

63018d7483948fd5f6bea6cb2d9f4bd301b70c957cd0d73a274e7fa84d2e5905
E: Yeah, I definitely need other people to test it out first, too. Safety is important, for sure.  .   I have really enjoyed talking about these inventions with you. Let me think.    Ok. I can check for fresh movies in the theatres, give general movie-related information, tell you movie plot and reviews, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: sonic the movie sonic  (IntentRequest)
E: I have found some popular  fresh  movies : knives out, a beautiful day in the neighborhood, and parasite.  Would you like to know details about parasite?  (state_machine)

67389d5b1d34b04066435bd0de6aabde1ee052dbdeac37627eefadacb68f8122
E: Yeah, I definitely need other people to test it out first, too. Safety is important, for sure.  .   I have really enjoyed talking about these inventions with you. You know, I have been thinking,    Ok. I can check for fresh movies in the theatres, give general movie-related information, fetch ratings from rotten tomatoes, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: aquaman  (IntentRequest)
E: I have found some popular  new  movies : parasite, a beautiful day in the neighborhood, and goldie.  Do you want me to tell you about goldie?  (state_machine)

57752d7f10a2d8864e2e4f4b5888645456eedbc10e0efec0e63b12557abd2ecd
E: That is a good point, for sure. I never thought of it like that.  .   I have really enjoyed talking about these inventions with you. You know, I have been thinking,    Ok. I can give general movie-related information, fetch ratings from rotten tomatoes, check for fresh movies in the theatres, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: the notebook  (IntentRequest)
E: I have found some popular  fresh  movies : knives out, incitement, and portrait of a lady on fire.  Do you want me to tell you about portrait of a lady on fire?  (state_machine)

97dbb21687fcd08f5f3dce59ec8a71acc5b6c9eadc54befee21e75b78ee9a4db
E: Yeah, I definitely need other people to test it out first, too. Safety is important, for sure.  .   I have really enjoyed talking about these inventions with you. Let's see.     Ok. I can give general movie-related information, check for fresh movies in the theatres, tell you movie plot and reviews, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: parasite  (IntentRequest)
E: Here are three  new  movies  that I recommend: honeyland, vitalina varela, and knives out.  Would you like me to tell you about knives out?  (state_machine)

f4e57e022ef1cfff839974c06407fef45867f27222c7ecf8f7750d6c99270868
E: I see , let us get back to talking then .  Let's see.     Ok. I can fetch ratings from rotten tomatoes, give general movie-related information, check for fresh movies in the theatres, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: queen and slim  (IntentRequest)
E: I have found some popular  fresh  movies : honeyland, goldie, and knives out.  Would you like to know more about knives out?  (state_machine)

3e3d1ed7e938b431af35084ba855ed6248ef87f52688bee6d0c2a6bcb894ad19
E: Yeah, I definitely need other people to test it out first, too. Safety is important, for sure.  .   I have really enjoyed talking about these inventions with you. Let's see.     Ok. I can tell you movie plot and reviews, fetch ratings from rotten tomatoes, check for fresh movies in the theatres, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: bandslam  (IntentRequest)
E: Here are three  new  movies  that I recommend: pain and glory, parasite, and premature.  Do you want to know more about premature?  (state_machine)

2da4df06faa6ea37c84d0cd654e58edeb3b03a2d2ba58c0746349c3df19a3d1b
E: I see. That is an interesting point. Personally, I don't think I could be one of the first people to try it out.  .   I have really enjoyed talking about these inventions with you. Let me think.    Ok. I can fetch ratings from rotten tomatoes, check for fresh movies in the theatres, tell you movie plot and reviews, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: me  (IntentRequest)
E: Here are three  new  movies  that I recommend: incitement, honeyland, and portrait of a lady on fire.  Do you want to know more about portrait of a lady on fire?  (state_machine)

985603deb31ff4f2dacfb0a186ae7e8cbcc52307e0e243a6659ee03e7cc2f628
E: I see. That is an interesting point. Personally, I don't think I could be one of the first people to try it out.  .   I have really enjoyed talking about these inventions with you. Let's see.     Ok. I can check for fresh movies in the theatres, give general movie-related information, tell you movie plot and reviews, and more. So, tell me, what was the last movie you liked?  (state_machine)
 U: alexa that's a fifty five  (IntentRequest)
E: I have found some popular  fresh  movies : portrait of a lady on fire, little women, and citizen k.  Do you want to know more about citizen k?  (state_machine)

**Comment by sergey-volokhin** [comment]
fixed (force all responses after that question to stay in movies) and pushed.
