### ISSUE TITLE
Pets bug

### ISSUE THREAD

**Issue by sergey-volokhin** [emora-chat/emora#117]
Pets component says "i liked learning about your experiences with pets" even if there was no conversation about pets. Probably should check that at least one turn was inside pets:

TTS: I seem to have gotten my signals crossed and I'm not sure what to say to that at the moment. Why don't we talk about something else? I've recently started learning about pets, but I also know a lot about movies and music.
ASR: no, 
TTS: I have really liked learning about your experiences with pets. Let me think.     I see. I find sports so exciting, no matter if I am watching or playing them.

**Comment by dongxiangjue** [comment]
??? I think this response "i liked learning about your experiences with pets" is not generated from pets component.
