### ISSUE TITLE
VideoGames: Some initial suggested changes

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#120]
I've attached a file with some suggestions for initial video games component based on a few conversations I've had with it, but good start!

[videogame_suggestions.txt](https://github.com/emora-chat/emora/files/4309488/videogame_suggestions.txt)

In addition,

A. State.RECOMMEND_POKEMONGO/RECOMMEND_OVERWATCH/RECOMMEND_MINECRAFT doesn't have any outgoing transitions (so it breaks if we get into this state)

B. This sequence doesn't really make too much sense:

```
S: wow it sounds pretty fun. actually, i would love to talk about some console games that i like personally
U: sure
S: right, i actually have many friends interested in this game. oh, by the way, i also like minecraft, which is a sandbox video game. it has been released for over 10 years now and it is still extremely popular. 
```

**Comment by Programmer01001101** [comment]
Since I no longer develop the video games component, I 'll close this issue :)
