### ISSUE TITLE
Travel: Stuck in Error Loop

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#121]
The "Interesting..." utterance should not repeat back-to-back like it does in this example. There should be less repetitive error-handling in place.

Example:

Alright. Besides sports, there are also some interesting events in san francisco .Would you like to know one?

do you know about beijing

Interesting. I am not quite familiar with this aspect of san francisco What about talking about something that I know, like interesting events there?

no

Interesting. I am not quite familiar with this aspect of san francisco What about talking about something that I know, like interesting events there?

**Comment by dongxiangjue** [comment]
fixed and updated
