### ISSUE TITLE
Travel: Macros are breaking

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#124]
The travel component is initialized once and shared across all users. It looks like you are storing information in your Macros in lists (like self.db_keys), which means that any updates you make to these lists within your Macro will persist across users. It is not specific to a single user. 

These Macros seem to be causing problems, since getting into states that use them are causing the system to throw failures. You should not be storing any information in your custom Macros. You should store information per user in the variable dictionary, since this is reloaded per user.

This would not be something you can reproduce locally, because locally there is just a single user (you). When it is deployed though, we have many users all accessing the same component across time.

**Comment by dongxiangjue** [comment]
fix
