### ISSUE TITLE
Pets: Natex is being spoken as a response due to improper usage

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#126]
I have seen in the logs that some utterances Pets is giving out actually contain Natex in them. This is due to improper Natex syntax and should have been discovered in your testing. Due to the number of errors we are seeing in Live, you really need to do more rigorous testing before you give me the changes. Make sure you test all transitions you have added so we can avoid this as much as possible. 

Example I have seen:

State: pet|State.FIRST_PET_OTHER_NAME",
Response: "{Cool,Wonderful,Wow, Awesome}! Sounds interesting.   I guess it must have a cute name. What is its name?",

**Comment by dongxiangjue** [comment]
Fixed. I also checked other states, but only found this one.
