### ISSUE TITLE
Movie Component: Error observed

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#13]
Last few turns of dialogue before the error happened:

U: lets talk about movies
E: Ok. I can check for fresh movies in the theatres, fetch ratings from rotten tomatoes, give general movies and tv shows information, and more. So, tell me, what was the last movie you liked?
U: the bounty hunter **(MOVIE BROKE HERE)**
E: Chasseur de primes is a Lucky Luke adventure written by Goscinny and illustrated by Morris. What else would you like to know? 

Log found here: https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=cobot-stack-BetaBotServicemovies-container-log;stream=e03d62157a68cf471e499d8500663789a599283dc52a202ccab5b7dd37bfd986;start=2019-12-03T04:49:30Z
at timestamp 00:22:12

![Screen Shot 2019-12-04 at 12 24 18 AM](https://user-images.githubusercontent.com/44447807/70115077-96a52980-162c-11ea-8b5d-82e258fa13c4.png)

**Comment by TheJdxfh** [comment]
fixed, pull request created

**Comment by sergey-volokhin** [comment]
fixed. pull request created
