### ISSUE TITLE
Sports: Missing space; phrasing suggestion.

### ISSUE THREAD

**Issue by harshita-sahijwani** [emora-chat/emora#134]
The following response is missing a space after the '.' before 'Would', which makes Alexa pronounce it as "car dot Would". 

"My friend's dads are always watching sport games. They usually have to listen to the radio if they are in the car.Would you be interested in watching sports games while riding in a car?"

Also, changing "My friend's dads" to "All my friends' dads" might be less ambiguous. (My friend's dads sounds like a particular friend has 2 dads (which might anger conservative users, I don't know).)

**Comment by harshita-sahijwani** [comment]
Other responses from the sports component also have space missing after '.'. e.g. "Wow, you are actually the first tennis fan i have met today. But I am sorry that i know little about tennis.On the contrary, I actually know a lot about basketball. Do you play or watch basketball?" has a missing space before "On"

**Comment by sefinch** [comment]
Ruixiang, the first response is a transition from sports to selfdriving, so I fixed it, but if you could look for other occurrences within the sports component that would be good too.

**Comment by Programmer01001101** [comment]
Thanks for the note. I've fixed the error you noted and checked other NLGs in the sports component. But I'm not sure if all of the errors are fixed. Please send me a note if you find more of these mistakes!
Thanks again!
