### ISSUE TITLE
Sports: typo and too long response

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#139]
This is quite a lengthy response and takes a while for emora to say it.

That is nice. By the way, I could tell you some interesting NBA matchups that I liked during this season. These are very interesting games, you could watch replays of these games since we do not have live games anymore for his season. For example, Team Atlanta and team Charlotte had a really wonderful match, team Atlanta only won by 5 points two weeks ago. Do you want to know details about this matchup?

Also "his" ==> "this"

**Comment by Programmer01001101** [comment]
Since Emora could no longer talk about recent games now, i think this is no longer a problem
