### ISSUE TITLE
Opening component - repeated "what interests you"-esque questions

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#14]
E: Hi, this is an Alexa Prize Socialbot. What can I call you?
U: june
E: Good morning. Nice to meet you june. So, can you share your feelings today?
U: i guess what do you want to know
E: Oh, I am glad you asked, I am feeling fine today. **Anything interests you today june?**
U: maybe cars or something
E: Allright, that was good to know. So june, **what interests you today?**

**Comment by boslbi92** [comment]
done
