### ISSUE TITLE
Movies: Repeating the same question

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#141]
Ok. tell me, what was the last movie you liked?

no

I can check for fresh movies, give movie information, tell trivia about movies, and more. So, Would you like to know current blockbusters?

sure

Here are three new movies that I recommend: cabaret maxime, my boyfriend's meds, and vivarium. Do you want me to tell you about vivarium?

sure

vivarium is a drama and mystery movie, starring jesse eisenberg and imogen poots, directed by lorcan finnegan, with rating 78 out of 100 according to rotten tomatoes. It premieres on March 26 2020, Would you like me to tell you the plot of vivarium?

no

Ok. tell me, What movie genres do you prefer?

comedy

Me too! I love a good laugh as much as the next robot. Ha-ha, classic humour. What is your favorite comedy movie?

i dont know

Oh well. You have a very good taste in movies. tell me, What movie genres do you prefer?

**Comment by sergey-volokhin** [comment]
fixed in latest pull request
