### ISSUE TITLE
Movies: confusing trivia

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#142]
Some of the trivia doesn't make a lot of sense when it is said out loud.

Example:

Would you like to know some fun trivia about movie happy feet?
sure

Here is a piece of trivia. The sixth computer-animated film to be produced at 2.35:1 after A Bug's Life (1998), The Polar Express (2004), The Incredibles (2004), Cars (2006), and Monster House (2006).. Do you want to know another?

**Comment by sergey-volokhin** [comment]
removed everything in parenthesis
