### ISSUE TITLE
Movies: cant exit

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#143]
This used to work but now it doesn't. Note: dm_suggested_topic will be "movies" in these "no" cases because the topic change question happens within the component, so the component needs to handle the "no" response and not produce a response.

------
Examples:
------

Oh well. You have a very good taste in movies. tell me, What movie genres do you prefer?

i said comedy

Me too! I love a good laugh as much as the next robot. Ha-ha, classic humour. Hey, we were talking about movie stuff for some time now. Do you still want to continue talking about movies?

no

Ok. What is your favorite comedy movie?

------

Ok. Hey, we have talked about movies for awhile. Would you like to talk more?
no

Ok. What actor do you like best?

**Comment by sergey-volokhin** [comment]
fixed in latest pull request
