### ISSUE TITLE
Movies: error

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#145]
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=cobot-stack-BetaBotServicemovies-container-log;stream=63ad602f0b2317afa243de5649384651ba104548b1e70a306ada32245e367ea6;refid=35352730612354456699115393055585877274386690868203225233;reftime=1585271267737

**Comment by sergey-volokhin** [comment]
fixed in latest pull request (82). forgot dynamoDB doesn't support empty strings.
