### ISSUE TITLE
Music: fails if it is the first topic selected after opening

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#146]
Hi , this is an Alexa Prize Socialbot . Happy to talk to you again , shannon . What was something fun that you did today?

i baked some cookies

Oh, okay. I heard you say baked . That is a great thing to do to keep yourself busy, especially in these times! I really enjoy hearing more about your life, so let's find other interesting things to talk about. So, there is a lot of new music that has come out recently. **Ok, well. I find it inspiring that we have so many different types of music to listen to.** 

==> this is the fallback if no music response is given

-----

This is the output of the DM for that turn:

[INFO]	2020-03-30T00:11:39.54Z	362c5cb3-d99c-42ac-92e4-c868362496ca	amzn1.echo-api.session.e1e98d71-e541-4537-a01e-2f529fff7f58 dialogue_manager - execute response: 
{
    "system_utterance": "Oh, okay. I heard you say baked . That is a great thing to do to keep yourself busy, especially in these times! I really enjoy hearing more about your life, so let's find other interesting things to talk about.    So, there is a lot of new music that has come out recently.   <<music>> Ok, well. I find it inspiring that we have so many different types of music to listen to.",
    "dm_suggested_topic": "music",
    "dm_suggested_content": null,
    "score": 0.7,
    "user_attributes": {
        "username": "shannon",
        "user_type": "freq",
        "transition_out": "Music and pets seem to be popular topics, but I also enjoy talking about movies."
    },
    "context_manager": {
        "dm_state": "music",
        "dm_vars": ...,
        "dm_prev_score": 0.7,
        "dm_prev_memory": ...
    },
    "performance": [
        0.10583615303039551
    ],
    "error": false

--------

This is the output of the music logs around that time:

00:11:25
result: Nothing interesting from music on the first turn

00:11:25
score: 0

00:11:39
query: I baked some cookies

00:11:39
context['topic_yes'] False context['topic_music'] False

00:11:39
new entity: False

00:11:39
context['classs'] recommendation

00:11:39
context['action']:

00:11:39
context['music_is_prev_component'] False

00:11:39
random suggestion: False False

00:11:39
msg['customizedintent']

00:11:39
[{'intent': 'General_ChatIntent',

00:11:39
'intent_prob': 0.75,

00:11:39
'topic': 'Phatic',

00:11:39
'topic_prob': 1.0},

00:11:39
{'error': True, 'message': 'Context missing: text'},

00:11:39
None]

00:11:39
result: There is nothing interesting from music

00:11:39
score: 0.0

**Comment by sergey-volokhin** [comment]
fixed in the latest pull request
