### ISSUE TITLE
Movies: Throwing exceptions

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#150]
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=cobot-stack-BotServicemovies-container-log;stream=cb7cd482347218ada2b23d2797d192eedab46eb2a13e317477ab08f9fe60e5da;refid=35371234092611421965968381694955729507260001674100801734;reftime=1586100992488

https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=cobot-stack-BotServicemovies-container-log;filter=Exception;start=P1D

**Comment by sergey-volokhin** [comment]
fixed
