### ISSUE TITLE
Music: Throwing exceptions

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#151]
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=cobot-stack-BotServicemusic-container-log;stream=2ab2d1fd23efca83a1adfe0033ae3b787bffc78fd9ffb20d25a34eb8c0476ca5;refid=35372243975591228024450295784714850357655679717156978688;reftime=1586146277207

https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=cobot-stack-BotServicemusic-container-log;filter=Exception;start=P1D

**Comment by sergey-volokhin** [comment]
fixed in the latest pull request
