### ISSUE TITLE
Sports: Lacking coverage of answers to "do you like sports"/"do you want to talk about sports" question

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#153]
It might be good to crawl the answers you get to this question and see what people say. I see a lot of variation and not all are handled well, like:

Examples: 

emora : Okay, interesting. Thanks for sharing that with me.      Do you like playing sports? I am a huge sports fan.
user : i love sports
--> sports doesn't give a response to this

Do you want to talk about sports? I am a huge NBA fan and I also have started to watch NFL recently.
user : i would like to talk about the n. b. a.
--> sports doesn't give a response to this

**Comment by Programmer01001101** [comment]
This problem has been fixed, thanks for reporting it!
