### ISSUE TITLE
Pets: doesn't handle if people do not like the conversation

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#155]
If people give a couple of no's in a row or indicate they are done, it would be good to end pets early.

Example:

emora : Oh ok, that's fine. It is indeed a big decision to introduce new members into your family or life. I know a lot about dogs. Although you won't keep a dog, would you like to know some information about dog breed, like bullmastiff ?
user : no
emora : Ok , besides various dog breeds, I also know lots of interesting things about dogs. Do you want to hear some?
user : no
emora : Well , I also know lots of movies about dogs. My favorite one is The Cave of the Yellow Dog .Would you like to know some details about it?
user : i don't wanna hear about dogs
emora : Ok , I also know some other movies about dogs. Would you like to listen one, like Marley and Me .Would you like to know some detail about it?
user : no
emora : Alright , I know lots of people have pets. What do you think are the benefits of keeping a pet?
user : i don't wanna talk about pets
emora : I understand. Although they may bring allergies or schedule disorder, we can't deny that they also bring so much joy into our lives.   I heard that some sporting events let pets attend. Many professional baseball games welcome dog owners and their dogs at Bark in the Park events during the regular season. Do you think this is a good idea?

**Comment by dongxiangjue** [comment]
Restructured pet component.
