### ISSUE TITLE
Music: (low priority) repetitive "favorite band" question

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#156]
Example:

emora ... Ok. What band do you enjoy listening to?
user : cannibal corpse is my favorite band
emora : I haven't heard about that band. Hey, that means i am learning, right? What music types do you like?
user : i like grunge metal ska fusion death metal cannibal music
emora : grunge. Good choice. What is your favorite grunge band?
user : cannibal corpse

I've seen a few examples where the original band question and the later genre band question get the same answer by the user, so it probably comes across as pretty repetitive.

**Comment by sergey-volokhin** [comment]
fixed
