### ISSUE TITLE
Movies: First conversation after update broke

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#158]
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=cobot-stack-BetaBotServicemovies-container-log;stream=50c97a05ee3e14a6c7d0daff5feef62c8199ed9f202e6926337daeed15296608;start=2020-04-06T03:27:30Z

**Comment by sergey-volokhin** [comment]
do you remember what the conversation was? what did you reply to the question "what was the last movie you liked?"?

**Comment by sefinch** [comment]
![Screen Shot 2020-04-06 at 11 46 14 PM](https://user-images.githubusercontent.com/44447807/78630356-849bf780-7867-11ea-9928-a2f7b37c6019.png)

**Comment by sergey-volokhin** [comment]
fixed in the latest pull request
