### ISSUE TITLE
Music: not able to move on after user answers "no" to keep talking about music, again?

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#159]
why dont you like concerts

i hate them

Right, I see. I see. We have been talking about music for awhile. Would you like to talk more?

no

Ok. Would you like to know what tracks are popular right now?

---

https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=cobot-stack-BetaBotServicemusic-container-log;stream=f775d2cb31da9323d6f1a0b500618dcf4e8e535ee17012a4ce8e9a649e54c8d0;start=2020-04-06T03:27:46Z

**Comment by sergey-volokhin** [comment]
fixed in the latest pull request
