### ISSUE TITLE
Pets: suggestions for newest push

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#160]
I've attached two files: one is an example conversation with the pets component and the other is some suggested updates/bugs based on the conversation.

[pets_example.txt](https://github.com/emora-chat/emora/files/4447575/pets_example.txt)

[pets_feedback.txt](https://github.com/emora-chat/emora/files/4447576/pets_feedback.txt)

**Comment by dongxiangjue** [comment]
Updated Q1-Q15 except "Q4: Pick one of the 3 "fact-sharing" options per conversation, don't do all of them in the same conversation: food, breed, or random facts". It will be updated in the next version.
