### ISSUE TITLE
Movies: repeats itself?

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#161]
Example:

Excellent choice. guardians of the galaxy has rating 91 out of 100 on rotten tomatoes, and is highly praised by critics. I like Space Odyssey 2001. One of the first films about artificial intelligence. Tell me, why do you like guardians of the galaxy?

it was funny

Interesting. I like Space Odyssey 2001. One of the first films about artificial intelligence. Do you want to hear some fun facts about movie guardians of the galaxy?

**Comment by sergey-volokhin** [comment]
it's not repeating. i acknowledged the choice user made, told him the rating. next i propose to tell user fun trivia about the movie he liked, which he probably didn't know.
should i correct the phrasing?

**Comment by sefinch** [comment]
It repeats the space odyssey part, when sharing emora's preference.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
