### ISSUE TITLE
Sports: Incorrect information & Utterance typos

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#168]
Here are some issues I noticed while testing the latest push:

--------------------------------------------------------------------------------------------------

great. i think bernardo silva is a very good player. As for me, my favorite player actually no longer plays in the England Premier League anymore and he currently plays for FC Barcelona. Guess who he is？

> who

no, actually, my favorite player is Lionel Messi. do you know him? what do you think of him?

==>

I dont think Messi ever played in the Premier League.

I know we had discussed this at one of the meetings, but after interacting with it a few times, it is weird/seems inconsistent that the favorite player is not in the EPL, but Emora can only talk about the EPL. Maybe it would be better to choose someone who is in the EPL.

--------------------------------------------------------------------------------------------------

thanks for your opinion we have talked a lot about soccer now. thanks for talking with me. by the way, do you watch basketball?

==> 

this system response has two parts which say "thanks for x", which is kind of repetitive

--------------------------------------------------------------------------------------------------

Haha, gotcha.  Let us continue to talk about baseball. I do watch MLB sometimes.  Do you watch MLB?

> yes

I am so glad that you do watch England Premier. Guess which team in England Premier is my favorite?

> what

no, actually,  my favorite MLB team has been the Yankees. If MLB were not shutdown due to the coronavirus outbreak, I acutally think they have a good chance of winning the championship this season. which team is your favorite?

==>

the system response seems to be messed up for responding to user's answer to "do you watch MLB"?

**Comment by sefinch** [comment]
I fixed the last bug I reported, since it was the most critical and I need to push some other people's stuff too. I also modified the phrasing reported in the second bug to mitigate it for now. I didn't touch the first one.

I'll push the updated version to dev in about 10 minutes.

**Comment by Programmer01001101** [comment]
Thanks so much for pointing out and fixing the bugs. I have fixed the first bug --- i've changed Emora's favorite player to  'Kevin De Bruyne' .
