### ISSUE TITLE
News: Split into chunks

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#170]
A sequence of five back-to-back distinct news segments is probably a bit monotonous. 

I shared the sample conversations with Jinho and he suggested giving one news segment at a time, and then we can insert the breaking news in between other components as an interesting break.

For this to work, the overall news state flow should look like:

`give_news -> acknowledge_user_response -> end`

(aka it shouldn't loop itself, although it may be good to handle if the user explicitly asks for another news as part of their response)

And we will just transition into `give_news` and then out of `end` between some components

**Comment by harshita-sahijwani** [comment]
giving one news at a time now
