### ISSUE TITLE
Movies: error

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#175]
Just pushed your update and it broke.

https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=cobot-stack-BetaBotServicemovies-container-log;stream=4a8bda1d6895ac9ddb645acf1c8ac05f08dd556dd0730c52a7fcb83399765265;refid=35383508514335553006112886971460345139398427583818104895;reftime=1586651396594

![Screen Shot 2020-04-11 at 8 31 12 PM](https://user-images.githubusercontent.com/44447807/79057801-71a47100-7c33-11ea-879c-22d89b1a79a5.png)

**Comment by sergey-volokhin** [comment]
fixed and pushed
