### ISSUE TITLE
News: Incomplete responses

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#176]
It seems like the systems responses are still incomplete for user responses. All but the first news are missing a "no" response.

[
    {
        "title": "Tesla's working on making ventilators from car parts",
        "summary": "Tesla engineers are working on a ventilator made largely from car parts. ",
        "details": "The prototype ventilator includes a backup battery and self-contained air supply that could allow it to work when not plugged into hospital power and oxygen supplies.",
        "follow_up_question": "Isn't it remarkable that automakers like Tesla and Ford are helping to meet the increased need for ventilators?",
        "follow_up_response_for_yes": "They posted a YouTube video last week, explaining how they are re-purposing various auto parts for the much needed medical devices.",
        "follow_up_response_for_no": "I hope we contain the virus soon.",
        "url": "http://rss.cnn.com/~r/rss/cnn_topstories/~3/hmB60pJEswo/index.html",
        "date": "April 6th",
        "source": "CNN"
    },
    {
        "title": "NASA is showing you the picture the Hubble Space Telescope took on your birthday",
        "summary": "NASA is celebrating the Hubble Space Telescope's 30th year in orbit since its launch in April 1990.",
        "follow_up_question": "Isn't that interesting?",
        "follow_up_response_for_yes": "You can even look at the picture the Hubble Space Telescope took on your birthday on their website.",
        "follow_up_response_for_no": "",
        "url": "http://rss.cnn.com/~r/rss/cnn_topstories/~3/b2kuRD4ZIeU/index.html",
        "date": "April 11th",
        "source": "CNN"
    },
    {
        "title": "Kroger and Walmart test one-way aisles as a coronavirus preventative measure",
        "summary": "Kroger and Walmart have implemented one-way aisles in some stores to encourage physical distancing during the coronavirus pandemic.",
        "follow_up_question": "Have you encountered one-way aisles during your recent visits to the grocery store?",
        "follow_up_response_for_yes": "It is good that your store is taking these steps to protect your health.",
        "follow_up_response_for_no": "",
        "url": "http://rss.cnn.com/~r/rss/cnn_topstories/~3/jEZijKDmlF0/index.html",
        "date": "April 6th",
        "source": "CNN"
    },
    {
        "title": "Apple, Google plan software to slow virus, joining global debate on tracking",
        "summary": "The tech companies Apple and Google will work together to create contact tracing technology that relies on cell phones to slow the spread of the coronavirus.",
        "follow_up_question": "Isn't that wonderful?",
        "follow_up_response_for_yes": "If the user is found to be infected, people who have been near them can be notified.",
        "follow_up_response_for_no": "",
        "url": "http://feeds.reuters.com/~r/reuters/technologyNews/~3/TckL6CjXg4M/apple-google-plan-software-to-slow-virus-joining-global-debate-on-tracking-idUSKCN21S1TT",
        "date": "April 11th",
        "source": "reuters"
    }
]

**Comment by harshita-sahijwani** [comment]
filled in responses for no
