### ISSUE TITLE
New Attribute Request : "stay_at_home"

### ISSUE THREAD

**Issue by Programmer01001101** [emora-chat/emora#191]
Hi James,

I remember that in your "coronavirus component", you ask the user if he/she has been staying at home, I wonder if it is possible for you to add a "stay_at_home" attribute to the user attribute table, which takes a boolean value to indicates whether the user has been staying at home.

With this attribute, I will be able to "guess" if the user has any chance of playing sports recently.

**Comment by jdfinch** [comment]
Right now my coronavirus component doesn't ask anything about the user staying at home (maybe you're thinking of something Jason's does?). If I update to learn this from the user I'll make sure to put it in the wiki.

**Comment by Programmer01001101** [comment]
Got it, thanks
