### ISSUE TITLE
Live version for sports does not work

### ISSUE THREAD

**Issue by Programmer01001101** [emora-chat/emora#197]
I happened to chat with Emora with "lets chat", and found that the live version of Emora for sports does not work quite so well. I've tried to look at logs, but I did not find the log of the conversation.  I also pulled the latest dev version, and it seemed that it works well on the current dev branch. 

The conversation was :

> E: Hi , this is an Alexa Prize Socialbot . Happy to talk to you again .    I am really excited to get to know you better.   What did you get up to today?
> 
> U: lets talk about sports
> 
> E:  For sure! I am a big sports fan. What is your favorite sport?
> 
> U : basketball
> 
> E : , i remember that we have talked about basketball before, am I correct ?
> 
> U : yes
> 
> E: I see. Well, I find sports so exciting, but I have encountered many people who don't.

Actually, in the dev, the conversation is 

> E: Hi , this is an Alexa Prize Socialbot . Happy to talk to you again .    I am really excited to get to know you better.   What did you get up to today?
> 
> U: lets talk about sports
> 
> E:  For sure! I am a big sports fan. What is your favorite sport?
> 
> U : basketball
> 
> E : , i remember that we have talked about basketball before, am I correct ?
> 
> U : yes
> 
> E:  thats right. we had a great conversation last time. that conversation was very memorable to me.   By the way, do you know that nba got shutdown this season because of the coronavirus outbreak?

It seems that the live version is not the same as the dev version. Do you know what went wrong?

**Comment by sefinch** [comment]
im pretty sure i found a bug that caused this to happen in the sports code last night and fixed it in this morning's push but am monitoring
