### ISSUE TITLE
Unknown error in conversation

### ISSUE THREAD

**Issue by Programmer01001101** [emora-chat/emora#202]
Hi,

When I was testing locally, I sometimes ran into the following error. But I could not reproduce the same error with the same conversation sequence with exact same version of Emora. I don't know if this is an issue.

<img width="1436" alt="Screen Shot 2020-05-20 at 23 12 32" src="https://user-images.githubusercontent.com/32470722/82520981-6b879700-9af3-11ea-96d6-f4500df5a0f1.png">

**Comment by sefinch** [comment]
This is a local testing of cobot-interactive mode error, something to do with getting the ASK Event from Amazon. It could be a timeout problem or something but I dont know. You can post in the Amazon Slack if you this is impeding your progress.
