### ISSUE TITLE
Sports conversation initiation failing

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#204]
It looks like sports is giving responses, even when dm_suggested_topic is not set to sports, which is interfering with its later invokations. Sports will only be selected if the dm_suggested_topic var is set to it, so it can ignore all other cases.

Example:

open atlanta chatbot

Hi , this is an Alexa Prize Socialbot . Happy to see you back , sarah . I am really excited to get to know you better. What did you do today?

played sports

Oh, sports ? It seems like a lot of people are spending this extra time at home getting into a good exercise routine. Is that something you are trying to do too?

no

Well, you never know. You just might get into a really good routine anyways, without even trying. Once we can get together with others in groups again, you could always try playing some team sports for a fun workout, too. I see. Well, I find sports so exciting, but I have encountered many people who don't.

![Screen Shot 2020-05-23 at 5 51 07 PM](https://user-images.githubusercontent.com/44447807/82741250-2eebb380-9d1e-11ea-8772-862227ef8768.png)

**Comment by Programmer01001101** [comment]
Thanks for pointing it out. 
I have fixed the bug and sent a pull request.
