### ISSUE TITLE
News: Error

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#21]
News is currently deployed to Beta but it keeps returning an error. Logs at https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logStream:group=cobot-stack-BetaBotServicenews-container-log;streamFilter=typeLogStreamPrefix

![Screen Shot 2019-12-09 at 3 38 29 PM](https://user-images.githubusercontent.com/44447807/70471032-64ffe880-1a9a-11ea-9776-abdd6ac0d01d.png)

**Comment by harshita-sahijwani** [comment]
I fixed the context_manager_keys for the news component in emora.py
