### ISSUE TITLE
Opening: Errors in log

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#24]
See log file: https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=cobot-stack-BetaBotServiceopening-container-log;stream=9ea4b42e2b19ca80fa043460907d2fbcf0a3fb425f518ce98012ffa399a5e4bb;start=2019-12-10T19:18:12Z

**Comment by boslbi92** [comment]
fixed
