### ISSUE TITLE
DynamoDB table for user-specific information

### ISSUE THREAD

**Issue by jdchoi77** [emora-chat/emora#25]
Create a DynamoDB table for user-specific information.  The entry gets populated whenever a new `user_id` is encountered.  The key is `user_id` and the value is a dictionary comprising:
* name: str
* gender: str
* hobbies: List[str]
* favorite_movie: List[str]
* favorite_food: List[str]
* favorite_book: List[str]

**Comment by sefinch** [comment]
Cobot has a default user_attribute table that gets populated for each new user based on user_id. We can save any fields that we want to it, and retrieve them during the conversation.
