### ISSUE TITLE
DynamoDB table for global information

### ISSUE THREAD

**Issue by jdchoi77** [emora-chat/emora#26]
Create a DynamoDB table for global information.  Here is an example:

```python
{
    names: {
        'james': {
            'count': 0,
            'hobbies': {'basketball': 3, 'cooking': 1},    # count of each hobby
            ...
        },
        ...
    genders: {
        'male': {
            'count': 0,
            'hobbies': {'basketball': 12, 'cooking': 4},    # count of each hobby
            ...
        },
        'female': {
            ...
        }
    }
}            
```

**Comment by sefinch** [comment]
Creation of GlobalUserTable completed. 
Saving of statistics of user attributes into GlobalUserTable during conversations completed.
Documentation started. https://github.com/emora-chat/emora/wiki/User-Attributes-Schema

To do
-------
Script for automatically modifying user attribute schema in tables, if want to add more attributes later.
Figure out interface for retrieving values from GlobalUserTable.

**Comment by sefinch** [comment]
Script for automatically modifying user attribute schema in tables completed.

To do
-------
Interface for retrieving values from GlobalUserTable

**Comment by sefinch** [comment]
Completed the API interface for retrieving values from GlobalUserTable
Updated documentation of API: https://github.com/emora-chat/emora/wiki/User-Attributes-Schema

To do
--------
Complete full example of saving user attribute and using global user attribute information in a remote module

**Comment by sefinch** [comment]
Redid Global User Attribute updating

Offline procedure now using scheduled task on AWS Lambda (less limitations/latency effect on changing user attributes per component)

API for retrieving global attributes tested
