### ISSUE TITLE
Opening: asking for the user name

### ISSUE THREAD

**Issue by jdchoi77** [emora-chat/emora#27]
- [x] Add more varieties to the question
    * e.g., may i have your name?
    * e.g., may i ask your name?
    * e.g., how may I address you?
    * e.g., how may I call you?
- [x] Record the user's name to the user-specific table (#25) as well as the global table (#26).

**Comment by sefinch** [comment]
Changing assignee, recording username in user-specific and global table is completed in new opening-state-machine component

**Comment by sefinch** [comment]
These name-asking alternatives are added:

What can I call you?
What name would you like to me to call you?
What name would you like to me to use for you?
May I have your name?
What should I call you?
