### ISSUE TITLE
Opening: acknowledging user's name

### ISSUE THREAD

**Issue by jdchoi77** [emora-chat/emora#28]
Add alternative ways of acknowledging user's name:

- [ ] Appreciation
    * e.g., That's a _cool_/_cute_/_pretty_ name
    * e.g., I like how your name sounds
    * e.g., _James_ means _Gift of All Gods_ (https://www.names.org/n/james/about)
- [ ] Stats about the name (#27)
    * e.g., you are the _3rd james_ I talked to today
    * e.g., you are the _5th sarah_ I met this week
    * e.g., you are the _4th guy_ who called me today
- [ ] Hobbies from another person with the same name (#26)
    * e.g., I know another _guy_ named _james_ who likes _basketball_. Do you also like _basketball_? &rarr; pass to the `Hobby Component`

**Comment by jdchoi77** [comment]
@boslbi92, please apply the following logic to the opening component:

![dialogue_flowchart-Login](https://user-images.githubusercontent.com/1037146/70965633-54cda780-205e-11ea-9191-c98e7d4ed8dc.png)

![dialogue_flowchart-Profiling](https://user-images.githubusercontent.com/1037146/70965585-28b22680-205e-11ea-9ac1-fe2023cb7f96.png)

Please let me know if you have any question.  Thanks!

**Comment by sefinch** [comment]
Changing assignee, new vs freq vs infreq user openings are completed in new opening-state-machine component
