### ISSUE TITLE
Opening: alternative greeting

### ISSUE THREAD

**Issue by jdchoi77** [emora-chat/emora#29]
Instead of saying "Good morning/afternoon/evening" which is not globally consistent (e.g., time difference between US and Korea), let's customize the greeting to our local time as follows (without revealing our location):

* Good morning &rarr; It's too early in the morning for me.
* Good afternoon &rarr; it's been a long day.
* Good evening &rarr; it's getting dark where I live.

**Comment by sefinch** [comment]
changing assignee, new opening-state-machine component will handle this

**Comment by sefinch** [comment]
done
