### ISSUE TITLE
Opening: asking for user's day

### ISSUE THREAD

**Issue by jdchoi77** [emora-chat/emora#30]
When the user response to "how are you doing today", and If the user response is neural (e.g., it's fine/ok), moderately positive (e.g., good), or asking back about how Emora is doing (e.g., what about you, how is your evening going), Emora should talk about:

- [ ] its own activities (e.g., I played basketball for 2 hours today, so tired. Do you like basketball? &rarr; pass to the `Hobby Component`)
- [ ] someone else's activities (e.g., my friends are having final exams today. When was your last time to take an exam?)

**Comment by sefinch** [comment]
changing assignee, new opening-state-machine component will handle this
