### ISSUE TITLE
Critical: Opening seems to be bugged

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#34]
I think this is a partial duplicate of a previous issue, but I have noticed a few different types of errors occurring so I'm bumping the issue. Overall, Opening seems to be bugged because it isn't lasting more than one turn due to errors quite frequently. I'm not sure what is causing the errors in Opening (like if it is dependent on a different component or something).

I've added screenshots of an example of each error I've seen. Taken from this log: https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=cobot-stack-BotServiceopening-container-log;stream=8e57a2c239c2b7cb9a7240584806b109851b81f6a3c25c033d8885a86a4337ff;start=2019-12-12T16:54:07Z.

![Screen Shot 2019-12-13 at 12 23 10 PM](https://user-images.githubusercontent.com/44447807/70819355-07261600-1da4-11ea-9fd1-f86e881e35e8.png)
![Screen Shot 2019-12-13 at 12 22 45 PM](https://user-images.githubusercontent.com/44447807/70819356-07261600-1da4-11ea-83c2-aa61190737c4.png)

**Comment by boslbi92** [comment]
fixed
