### ISSUE TITLE
Movie 'my response' key error

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#35]
Newest merge of movies produced this error:

![Screen Shot 2019-12-18 at 2 04 20 AM](https://user-images.githubusercontent.com/44447807/71063604-0215ed80-213b-11ea-8f1d-7955fa1387f9.png)

https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=cobot-stack-BetaBotServicemovies-container-log;stream=e904a6662c1279ed7c2d3362cbb03f3a576311cce21237dd1d3ac21513fe208d;start=2019-12-17T06:39:39Z

**Comment by sergey-volokhin** [comment]
My bad. I thought i fixed that. 
Now I did.
