### ISSUE TITLE
Is dev:movies up to date? Error found after deploying to Beta

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#36]
I just pushed the latest version of dev to Beta, and movies broke in this conversation.

open atlanta chatbot
Hi, this is an Alexa Prize Socialbot. What can I call you?
sarah
Thats a cool name. Good evening, sarah. How are you feeling today?
fine
Glad to hear your evening is going well. So, what made you happy today sarah?
im excited for the holidays
That sounds very cool sarah! So, do you have something in your mind to talk about today?
lets talk about christmas
are you excited for the holidays
yes of course
what excites you the most
eating good food with my family
holiday food is delicious, i always curl up with a good holiday movie afterwards
what holiday movie do you watch
This might answer your question: In the United States, the next national holiday is Christmas Day this Wednesday. Do you have any other interesting topics in mind?
lets talk about holiday movies
hmm, i think its interesting that you thought of holiday movies. can you tell me more about your opinion on it?
i want to talk to you about movies
That sounds very cool sarah! So, do you have something in your mind to talk about today?

I found an error in the log, not sure exactly which utterance it came from.
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=cobot-stack-BetaBotServicemovies-container-log;stream=b32c729f7bcd56f23e67ec497b78de24b58e59aeff3134149179b8605aa20946;start=PT5M

![Screen Shot 2019-12-23 at 11 42 22 PM](https://user-images.githubusercontent.com/44447807/71394206-7e4a7e00-25de-11ea-960b-0020369e425c.png)

Also, each time Movies breaks, it isn't able to save the context so it always keeps breaking on subsequent turns because context is a Nonetype. It would probably be better to have an error catching condition for this, so that movies can potentially recover from errors on a particular utterance.

![Screen Shot 2019-12-23 at 11 42 44 PM](https://user-images.githubusercontent.com/44447807/71394205-7e4a7e00-25de-11ea-8407-631c9bd3441a.png)

**Comment by sergey-volokhin** [comment]
this is fixed but not yet pushed (entangled with the same commit as other issue fix, which i need to test)
