### ISSUE TITLE
Sports: favorite team and player

### ISSUE THREAD

**Issue by jdchoi77** [emora-chat/emora#41]
> **Task 1**
> Store the user's favorite team and player to the user table.

Given the following dialogue:

* Which NBA team is your favorite? &rarr; Chicago Bull.
* Who is your favorite NBA player? &rarr; Michael Jordan.

"Chicago Bulls" and "Michael Jordan" should be added as the user's favorite team and player in the user table.  Once they are added, Emora should no longer ask this question to the same user.

> **Task 2**
> Derive a small talk about the user's favorite team and player when the information is given.

Currently, Emora talks about her favorite team and player (other than the user's favorite player is Lebron James), neglecting user responses.  Emora should be able to make a small talk about the user's favorite team and player that can be automatically updated weekly (or even daily).

* Chicago Bulls has not been doing well this season. They've won only 15 out of 42 games.
* Michael Jordan is the GOAT. I wish he is still at Chicago.

> **Task 3**
> Talk different things about Emora's favorite team and player

Currently, Emora says the same thing over and over for her favorite team and player. Given the same user, it should never repeat what it had said before.

**Comment by Programmer01001101** [comment]
All the tasks above have been completed, let me close this issue : )
