### ISSUE TITLE
Sports: favorite sports

### ISSUE THREAD

**Issue by jdchoi77** [emora-chat/emora#42]
> **Task**
> Store the user's favorite sports in the user table

Given the following dialogue:

What is your favorite sports? &rarr; Baseball

"Baseball" should be added as the user's favorite sports in the user table. Once it is added, Emora should not ask this question to the same user.

> **Task 2**
> Derive a small talk about the user's favorite sports and make a transition to basketball.

Currently, Emora talks about her favorite sports, basketball, neglecting user responses. Emora should be able to make a small talk about the user's favorite sports and make a "smooth" transition to basketball.

**Comment by Programmer01001101** [comment]
Task 2 completed but possibly need some more improvements.

 **Case Soccer:**
- Emora: I love sports. My favorite sport is basketball. What is your favorite sport?
- User : Soccer
- Emora: Wow, you share the same interest with my best friend James. James is a big soccer fan, his favorite team is Barcelona. Although I do not play soccer, many people around me like it a lot. My favorite sport is basketball.  Do you play or watch basketball?

 **Case Tennis:**
- Emora: I love sports. My favorite sport is basketball. What is your favorite sport?
- User : Tennis
- Emora: Wow, you share the same interest with my best friend George. George is a big tennis fan, his favorite player is Roger Federer. Although I do not play tennis, many people around me like it a lot. My favorite sport is basketball.  Do you play or watch basketball?

 **Case Baseball:**
- Emora: I love sports. My favorite sport is basketball. What is your favorite sport?
- User : Baseball
- Emora: Oh, My friend told me that baseball is one of the most popular sports in the united states. Let me guess, are you from the united states?
- User: no
- Emora: Oh well. I could be wrong sometimes haha.  Let us continue to talk about sports. I love playing basketball.  Do you play or watch basketball?

 **Case Football:**
- Emora: I love sports. My favorite sport is basketball. What is your favorite sport?
- User : Football
- Emora: Oh, My friend told me that football is one of the most popular sports in the united states. Let me guess, are you from the united states?
- User: yes
- Emora: Haha, gotcha. Let us continue to talk about sports. I love playing basketball.  Do you play or watch basketball?

 **Case Ice Hockey:**
- Emora: I love sports. My favorite sport is basketball. What is your favorite sport?
- User : Ice Hockey
- Emora: Oh, My friend told me that ice hockey is one of the most popular sports in the canada. Let me guess, are your from canada?
- User: yes
- Emora: Haha, gotcha. Let us continue to talk about sports. I love playing basketball.  Do you play or watch basketball?

 **Case other sports:**
- Emora: I love sports. My favorite sport is basketball. What is your favorite sport?
- User : Swimming
- Emora: That is a great sport. I am sorry I only watch basketball. Do you play or watch basketball?
