### ISSUE TITLE
Sports: cannot handle "No".

### ISSUE THREAD

**Issue by jdchoi77** [emora-chat/emora#43]
The sports component cannot handle when the answer is "No" to the following question:

* Emora: Do you watch NBA?
* User: No
* Sorry, I'm not sure how to respond.

It should try to figure out what the user wants when the response is "No".

**Comment by Programmer01001101** [comment]
Emora now will redirect the user to another component if user says no

- Emora: Do you watch NBA?
- User: No
- Emora: okie dokie. I am sorry that I could only talk about NBA in the sports domain for now. Do you want to talk about something else? We could talk about recent movies or news if you like.

.
