### ISSUE TITLE
Sports: looping statements

### ISSUE THREAD

**Issue by jdchoi77** [emora-chat/emora#46]
After Emora says "My favorite player is Stephen Curry. I've been his fan since 2015. I'm sad that he didn't play many games because of his injury.", no matter what the user says, Emora keeps repeating the same statement. After this statement, Emora should lead the user to talk more.

**Comment by Programmer01001101** [comment]
Emora will tell user some random sports news afterwards. (For examples, NBA games where the final score is very close)

- Emora: My favorite player is Kawhi Leonard. I became his fan after witnessing him winning the championship last season. I really like his playing style.
- User: Ok
- Emora: By the way, I could tell you some interesting NBA matchups that happened recently, for example, As an away team, team Milwaukee beats Portland by 21 points a few days ago. Do you want to know more similar matchups?
- User: Yes
- Emora:  Team Toronto and team Portland had a really wonderful match, team Portland only won by 2 points last week. Do you want to know more similar matchups?
- (continues until the user says no)
- User: No
- Emora: That is everything that I could talk about sports so far. Do you want to talk about something else? I could update you with the most recent movies and news
- User: Movies
- Emora: Ok. I can check for fresh movies in the theatres, give general movie-related information, tell you movie plot and reviews, and more. So, tell me, what was the last movie you liked?
