### ISSUE TITLE
Sports doesn't handle utterance "i do" meaning "yes"

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#48]
Should be able to handle things like "i do", "i play", "i watch", etc. I've only used "i do" in the conversations I've had, not the others, so I'm not sure if they are already handled. This is probably a good opportunity to think about expanding the handled responses of other parts of your Sports component too (synonyms, etc.).

Example:

E: Wow, you share the same interest with my best friend James. James is a big soccer fan, his favorite team is Barcelona. Although I do not play soccer, many people around me like it a lot. My favorite sport is basketball. Do you play or watch basketball?

U: i do

E: Ok. I am sorry that I could only talk about basketball in the sports domain for now. Do you want to talk about something else? We could talk about recent movies or news if you like.

**Comment by Programmer01001101** [comment]
Thanks for pointing it out. This bug has been fixed.
