### ISSUE TITLE
Opening weird bug (repeats Alexa Prize greetings)

### ISSUE THREAD

**Issue by boslbi92** [emora-chat/emora#51]
-------------------- EmoraJan19 1.0 db5c5bfa4cff1f0bf2f6c7e17a70149b30d974b82bc703f7272f89fa0a5d0110 --------------------Q: let's chat [Phatic, OtherIntent]
A: Hi this is an Alexa Prize Socialbot. What name would you like to me to call you? [openingsm]

Q: i'm jenny [Phatic, General_ChatIntent]
A: sorry, i'm not sure how to respond. Why don't we talk about something else? Some things I know about are movies, sports, and pets, if you like. [none]

Q: okay let's talk about dogs [Science_and_Technology, Information_RequestIntent]
A: Hi this is an Alexa Prize Socialbot. I am happy to be talking to you. How are you today? [openingsm]

Q: i'm great how are you [Phatic, General_ChatIntent]
A: Thats good to hear. I am good too. If you dont mind can you tell me more about it? [openingsm]

Q: alexa stop [None, None]
A: It was nice talking to you. Goodbye. [None]

**Comment by sefinch** [comment]
Can you send me the log file from the opening module that was created for this conversation? It looks like opening died for some reason and restarted but the logs will tell more

**Comment by boslbi92** [comment]
-------------------- EmoraJan19 1.0 4b5693d6be42d84008def241d0c264402ebe618f8c139b6247d5232c8bde5331 --------------------Q: let's talk about animals [Science_and_Technology, Information_RequestIntent]
A: Hi this is an Alexa Prize Socialbot. What name would you like to me to call you? [openingsm]

Q: karen [Phatic, General_ChatIntent]
A: Well its nice to meet you karen . its getting pretty late for me here . How are you today? [openingsm]

Q: okay [Phatic, Acceptance]
A: That's understandable. Is there anything in particular that made you feel this way? [openingsm]

Q: just some uhhh relationships [celebrities, Acceptance]
A: Thanks for sharing that with me. What would you like to talk about today? [openingsm]

Q: animals [Science_and_Technology, Information_RequestIntent]
A: so, i think it is cool that you thought of animals. why is that on your mind? [fallbacktransitions]

Q: i don't know i think they're cool [Phatic, Opinion_ExpressionIntent]
A: Allright, so, do you want to talk about something else, like movies or sports? [pets]

Q: sports [Sports, Information_RequestIntent]
A: I love sports. My favorite sport is basketball. What is your favorite sport? [nba]

Q: cross country [Sports, Information_DeliveryIntent]
A: That is a great sport. I am sorry I only watch basketball. Do you play or watch basketball? [nba]

Q: no i don't like basketball [Sports, Information_DeliveryIntent]
A: Ok. I am sorry that I could only talk about basketball in the sports domain for now. Do you want to talk about something else? We could talk about recent movies or news if you like. [nba]

Q: uh i don't care [Phatic, General_ChatIntent]
A: Allright, so, do you want to talk about something else, like movies or sports? [pets]

Q: yeah [yes, Acceptance]
A: Hi this is an Alexa Prize Socialbot. I am happy to be talking to you. How are you today? [openingsm]

Q: good [Phatic, Acceptance]
A: Im glad to hear that. If you dont mind can you tell me more about it? [openingsm]

Q: i got to hangout with my friend today [Phatic, Acceptance]
A: Ok I see. What would you like to talk about today? [openingsm]

Q: subway surfers [attraction, Information_RequestIntent]
A: Allright, so, do you want to talk about something else, like movies or sports? [pets]

**Comment by boslbi92** [comment]
Check the statatables with these 2 conv ids, there are potentially more

**Comment by boslbi92** [comment]
-------------------- EmoraJan19 2.0 03e1948ae5c5e8768fe69f5933e624a8d3322ded35905e3c16a2c0bc3e3ba338 --------------------Q: let's chat [Phatic, OtherIntent]
A: Hi this is an Alexa Prize Socialbot. What can I call you? [openingsm]

Q: kimberly [Phatic, General_ChatIntent]
A: Nice to meet you kimberly . its getting dark where I live . How are you today? [openingsm]

Q: i'm pretty lonely [Phatic, General_ChatIntent]
A: I was hoping for a better day for you. If you don't mind talking about it what has made it such an unpleasant day for you? [openingsm]

Q: emmanuel call me back that i like [Phatic, General_ChatIntent]
A: Gotcha. What would you like to talk about today? [openingsm]

Q: how good oatmeal is for you [food, General_ChatIntent]
A: i dont know if ive thought of how good oatmeal in a while. can you tell me more about your opinion on it? [fallbacktransitions]

Q: i love oatmeal with peanut butter [food, Opinion_ExpressionIntent]
A: Hi this is an Alexa Prize Socialbot. I am happy to be talking to you. How are you today? [openingsm]

Q: i am good thank you [Phatic, General_ChatIntent]
A: Im glad to hear that. Why are you in such a good mood? [openingsm]

Q: i don't know [Phatic, Acceptance]
A: Gotcha. What would you like to talk about today? [openingsm]

Q: unrequited love [Entertainment_Movies, Information_RequestIntent]
A: Here are three  new  movies  that I recommend: midnight family, pain and glory, and little women. Do you want me to tell you about little women? [movies]

**Comment by sefinch** [comment]
Oh, I see, you are looking through the conversations from the weekend. This was an issue Jinho identified when it happened and I already pushed a patch over the weekend.
