### ISSUE TITLE
Music: cannot access several database tables

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#63]
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=cobot-stack-BotServicemusic-container-log;filter=Exception;start=PT6H

Excerpt from search in logs:

Exception on / [POST]
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the GetItem operation: User: arn:aws:sts::720500621654:assumed-role/cobot-stack-BotServicemusic-TaskRole-AQ9H7NFXX3QA/16cb7081-d39a-4dc2-916b-a87645e29a31 is not authorized to perform: dynamodb:GetItem on resource: arn:aws:dynamodb:us-east-1:720500621654:table/musicData_songs_f_artist

Exception on / [POST]
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the Scan operation: User: arn:aws:sts::720500621654:assumed-role/cobot-stack-BotServicemusic-TaskRole-AQ9H7NFXX3QA/16cb7081-d39a-4dc2-916b-a87645e29a31 is not authorized to perform: dynamodb:Scan on resource: arn:aws:dynamodb:us-east-1:720500621654:table/musicData_emerging

botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the GetItem operation: User: arn:aws:sts::720500621654:assumed-role/cobot-stack-BotServicemusic-TaskRole-AQ9H7NFXX3QA/16cb7081-d39a-4dc2-916b-a87645e29a31 is not authorized to perform: dynamodb:GetItem on resource: arn:aws:dynamodb:us-east-1:720500621654:table/musicData_billboards

**Comment by sergey-volokhin** [comment]
Fixed
