### ISSUE TITLE
Movie bug: context['movie'] is boolean when expected to be collection

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#64]
![Screen Shot 2020-01-26 at 12 53 00 PM](https://user-images.githubusercontent.com/44447807/73139325-ffac8a80-403a-11ea-8e51-83d99d374623.png)

Log: https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=cobot-stack-BotServicemovies-container-log;stream=8daa1436ebf0e38f67de26e48c7d7ff629cfc4e3dbe46771ba47abbf58eaf3ea;start=PT12H

**Comment by sergey-volokhin** [comment]
additional check added, fixed
