### ISSUE TITLE
Movie: no error-handling in place when context format is not expected, one error causes subsequent errors on following turns because of this

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#65]
If an error occurs that crashes the movie component(such as the context['movies'] being a boolean instead of the expected collection), movie components throws this error for many turns afterwords because the context was not updated. It would be better to have some recovery procedure in place to stop this sequence of errors.

![Screen Shot 2020-01-26 at 12 53 19 PM](https://user-images.githubusercontent.com/44447807/73139359-3c788180-403b-11ea-9021-1e2ccceba54c.png)

Log file: https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=cobot-stack-BotServicemovies-container-log;stream=8daa1436ebf0e38f67de26e48c7d7ff629cfc4e3dbe46771ba47abbf58eaf3ea;start=PT12H

**Comment by sergey-volokhin** [comment]
Automatic recovery added, but it will be reset, and not remember anything if it failed. Could be improved if I can retrieve second previous context, but that's not possible right now due to how contexts are retrieved for returning users (if I am not mistaken)
