### ISSUE TITLE
Movie: detects wrong genre?

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#66]
Conv id: e1753db9a0db0f87ee2b6467c6b66e259f3cf86a9c01ada304bfab972d7b9d88  

O: Hmm I'm not sure what you mean. What would you like to talk about today? I've recently become interested in sports but I have always enjoyed talking about movies. (openingsm)

I: science fiction (Information_RequestIntent, Entertainment_Movies)

O: Here is a good new comedy movie I think you might enjoy: jojo rabbit. It has rating 80 out of 100 on rotten tomatoes. Would you like me to tell you about jojo rabbit? (movies)
I: no (reject, Other)

**Comment by sergey-volokhin** [comment]
Fixed
