### ISSUE TITLE
Music: incoherent response ("I don't have any information on genre False")

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#67]
Conv id: e1753db9a0db0f87ee2b6467c6b66e259f3cf86a9c01ada304bfab972d7b9d88  

O: i do not believe ive thought of bruce springsteen in a while. can you tell me more about your opinion on it? (fallbacktransitions)

I: it's quite good (Opinion_ExpressionIntent, Entertainment_Music)

O: Sorry, I don't have any information on genre False (music)

**Comment by sergey-volokhin** [comment]
I could not reproduce the error. My guess is that the API i'm using failed for some reason. I added a better catcher.
