### ISSUE TITLE
Movies: unable to coherently respond if user mentions specific entity (movie or actor)

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#68]
Conv id: ced4ddcabcc02b56c3f78e32a5589704c298d59c014212828045c05ab7b4aa48

----------

I: well do you know the plot of spies in disguise (Information_RequestIntent, Entertainment_Movies)

O: Here are three  fresh  movies  that I recommend: a beautiful day in the neighborhood, the lighthouse, and pain and glory. Would you like to know more about pain and glory? (movies)
I: no thank you (TopicSwitch, no)

O: Okay. Is there anything else you want to know? (evibot)

I: do you know about the movie spies in disguise (Information_RequestIntent, Entertainment_Movies)

O: I have found some popular  new  movies : weathering with you, knives out, and synonyms. Do you want to know more about synonyms? (movies)

------

I: no do you know about the movie star wars (Information_RequestIntent, Entertainment_Movies)

O: I have found some popular  new  movies : queen and slim, cunningham, and little women. Would you like me to tell you about little women? (movies)

-------

O: Ok. What actor do you like best? (movies)

I: i like idina menzel (Acceptance, Entertainment_Movies)

O: I have found some popular  new  movies : once upon a time in hollywood, a hidden life, and zombi child. Do you want me to tell you about zombi child? (movies)

-------

**Comment by sergey-volokhin** [comment]
Unfortunately, my database of movies and actors does not cover every single one. and I can't react to things coherently if I don't know that they are entities. detecting a new entity in the utterance is tricky, and requires balance between thinking every utterance has an entity (and consequently forcing the conversation to pointlessly proceed in movie component), and thinking there is no entity in any turn that you couldn't detect entity in. that balance i could not figure out last year, but i will try to attend to it this year. 
or, if you have any suggestions on what you think I should do in this situation, feel free to message me on teams (or talk during a meeting)

'Star Wars' is not a movie name, it's a franchise. I will add franchises coverage for select ones a bit later.

**Comment by sefinch** [comment]
Gotcha, I wasn't sure if it was something like that or some bug that was happening, since it seemed to happen frequently for me recently. 

I'm not sure what the best solution is (obviously more coverage is always good, but thats hard). It could be useful to have some acknowledgement if it doesn't recognize the answer to the question, maybe with a lower score (for example, the "what actor do you like best" exchange in the original post).
