### ISSUE TITLE
Pets: needs some initialization changes

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#79]
To make pets compatible with Cobot in its current setup, the initial speaker needs to be set as the user and the Start state needs to include at least some user transitions out of it for this (even if they are just error transitions because you want the system to initiate the pets conversation).

**Comment by dongxiangjue** [comment]
I just pushed the update. Does it work now?

**Comment by sefinch** [comment]
Not quite. Test what the component does if the user doesn't say pet or pets on the first turn and update accordingly.

**Comment by dongxiangjue** [comment]
I added the transition and initialization and checked it. What about now?

**Comment by sefinch** [comment]
There seem to be several states where you are expecting the user to say something but your coverage is incomplete and (importantly) you do not have an error successor set up. The idea is that the error successor will catch the cases you do not think of ahead of time, so there must be an error successor for every state that has a user transition out of it. Otherwise, If i give a response it doesn't handle, the whole component crashes because of this.

**Comment by sefinch** [comment]
Making my last comment a new issue, since its no longer about the initialization.
