### ISSUE TITLE
Concert finding - Music Component

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#8]
For the following dialogue sequence, music component isn't able to find any concerts, according to the logs, but that probably should be told to the user instead of giving preference to a different component (the given answer comes from AIML):

Could you tell me artist, city or a month you would like to search the concerts for?

black eyed peas

If you could have any kind of robot what would it be?

**Comment by sergey-volokhin** [comment]
that's to do with our string matched "sensitive topics", not music fault

**Comment by sefinch** [comment]
if it was a sensitive topic flag, the response would say "there's no way of answering that". The fact that it chose a different component (AIML) means sensitive content flag was not given.

**Comment by sergey-volokhin** [comment]
Could you rerun the conversation and confirm that? I ran it locally with current version of the system, and my component did return an answer (you can see it in music_container log), but it was not picked up by dialog manager.
