### ISSUE TITLE
News: stuck in loop

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#83]
We have a response selection setup to suggest other topics for when no components have a response (it isn't perfect, but it tries to provide variety), but news is preventing that from occurring.

Convo example:

i didnt want that

espn cric info, on February 04, reported. Temba Bavuma admits recent discussions about his place in the side have weighed heavily on him | ESPNcricinfo. com. I can tell related news in the categories, sports, general, entertainment. Which one do you want to know?

none

Sorry, I didn’t catch that. Do you have any other interesting topics in mind?

no

I watched the news channel this morning, I have news in the categories sports, business. Which one would you like to know?

i dont want to talk about news

i think you are interested in news. why is that in your thoughts?

no

I watched the news channel this morning, I have news in the categories sports, business. Which one would you like to know?

i dont want any of the news

espn cric info, on February 04, reported. Temba Bavuma admits recent discussions about his place in the side have weighed heavily on him | ESPNcricinfo. com. I have related news in the categories, sports, general, entertainment. Which one do you want to know?

stop

**Comment by sefinch** [comment]
Is there any update on this? There is a pretty similar problem happening here. We have a response selection setup to suggest other topics for when no components have a response (it isn't perfect, but it tries to provide variety), but news is preventing that from occurring.

Convo snippet:

among various cat breeds what specific kind is your favorite

persian

. My news source about Persian just got fired, bad day for me. Would you like to talk about trending news?

yes

. I am not sure how to respond to yes. Would you like to talk about trending news?

yes

. I am not sure how to respond to yes. Would you like to talk about trending news?

no

. I am not sure how to respond to no. Would you like to talk about trending news?

no

. I am not sure how to respond to no. Would you like to talk about trending news?

**Comment by harshita-sahijwani** [comment]
I fixed the case where it doesn't respond to 'yes'. I don't know why news is getting picked to respond when the user says no. I return a score of 0.1 when news does not find anything relevant in its index for the user utterance. I changed it to 0, but news still gets picked up.

**Comment by sefinch** [comment]
Have you made a pull request or pushed this change?
