### ISSUE TITLE
Music: key error

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#86]
![Screen Shot 2020-02-07 at 11 52 14 PM](https://user-images.githubusercontent.com/44447807/74079402-f7722900-4a04-11ea-891a-728b87247f18.png)

**Comment by sergey-volokhin** [comment]
fixed and pushed to my branch

**Comment by sergey-volokhin** [comment]
actually requires additional testing

**Comment by sergey-volokhin** [comment]
now closed for sure
