### ISSUE TITLE
Pets: Incomplete user transitions

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#94]
There seem to be several states where you are expecting the user to say something but your coverage is incomplete and (importantly) you do not have an error successor set up. The idea is that the error successor will catch the cases you do not think of ahead of time, so there must be an error successor for every state that has a user transition out of it. Otherwise, If i give a response it doesn't handle, the whole component crashes because of this.

**Comment by dongxiangjue** [comment]
Updated transitions.
