### ISSUE TITLE
Sports: repeated exit utterance?

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#96]
![Screen Shot 2020-02-12 at 1 32 40 PM](https://user-images.githubusercontent.com/44447807/74372595-ef214180-4da8-11ea-9cad-b08c26d3e53a.png)

This is the CloudWatch log info:

![Screen Shot 2020-02-12 at 1 33 47 PM](https://user-images.githubusercontent.com/44447807/74372591-ee88ab00-4da8-11ea-9b52-dd975869fd05.png)

**Comment by Programmer01001101** [comment]
this problem has been fixed .
