### ISSUE TITLE
Pets: too many questions at once are asked to the user

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#97]
The Pets conversation would be improved if the user wasn't asked more than one question at a time. Its pretty safe to assume that most people cannot keep track of and answer more than one question. Here is an example of system utterances from Pets that should be improved on this dimension, but there might be some that I missed.

**Example**:

S: that ' s great! I love pets ! actually,  my favorite pet is german shepherd dog. Do you have any pets at your home now? If you have, What is it? is it a cat, a dog or other types of pets?

**Comment by dongxiangjue** [comment]
Updated to "Do you have any pets at your home now? like a dog, cat, or other animals?"
