### ISSUE TITLE
Pets: too much information in one utterance

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#98]
Do not put too much information into one system utterance. People cannot pay attention to more than a couple of things at a time. Of course, you should use subsequent turns to include additional information that you want to cover, if there is more than one turn's worth.

**Some examples (not an exhaustive list):**

1. Talking about Emora's favorite is a lot of distinct information to handle on top of receiving the breed question. 

    S: Wow! that 's great! What is its breed? I mean it 's turkish angora, toyger, or other cat breed? Actually, my favorite cat is toyger.

2. Having a list of items more than one or two long is too many.

    S: that ' s nice! you know, there are lots of food that cats can 't eat, like alcohol, chocolate, coffee, tea, energy drinks, cheese, milk, raw meat, raw eggs, raw fish, grapes, raisins, onions, garlic, xylitolts.

**Comment by dongxiangjue** [comment]
1. Deleted redundant information;
2. Updated it into a random list.
