### ISSUE TITLE
Pets: dog breed bug

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#99]
There seems to be a bug where Emora lists a specific dog breed but if the user mentions it, she says she doesn't know the breed.

**Example**

S: Nice choice! I like dogs, too! Among various dog breeds, which one do you like the best? I mean, like german shepherd, golden retrieval, husky, or other dog breed?

U: husky

S: Cool! although i know lots of dog breed, I 'm not quite familiar with the one you mentioned, but i ' m sure they must very lovable in some way. Also, I know lots of interesting things about dogs, would you like to listen one?

**Comment by dongxiangjue** [comment]
This was the answer it should give because the information of husky was not in database at that time. I just added it into the database in the latest version.

**Comment by sefinch** [comment]
I see. For future reference, you should not list something that you cannot handle. For this specific case, husky should not have been in the system utterance "I mean, like german shepherd, golden retrieval, husky, or other dog breed?" unless saying husky would be recognized.

**Comment by dongxiangjue** [comment]
Ok, because I didn't notice the name of the husky is "siberian husky" in database.
